language: android

android:
  components:
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-26

script:
  - ./gradlew build

after_success:
  - bash <(curl -s https://codecov.io/bash)